### PR TITLE
Fix burst only

### PR DESCRIPTION
**Pull request by toad**
Various cleanups, mostly directed at fixing logging errors. Relatively low risk but could conceivably change connectivity behaviour on non-NATed nodes.

### CODE REVIEW

**Comment by toad** [comment]
I've added a bunch more fixes, I think this is reasonable now. Please re-review. :)

**Comment by toad** [comment]
Yes, DarknetPeerNode's setStatus method calls PeerNode's setStatus and then changes the value in some cases. I will add some javadocs.

**Comment by toad** [comment]
I'll try not to add more unrelated bugfixes to this branch! Please review. Thanks.

**Comment by Thynix** [comment]
Anyone want to review this?

**Comment by ArneBab** [comment]
@toad could you explain what the non-logging changes here do?

**Comment by nextgens** [comment]
Looks good to me

**Comment by Thynix** [comment]
Can I trouble someone to resolve the merge conflicts? I attempted fixing them but it wasn't exceedingly clear to me what was intended.

**Comment by Thynix** [comment]
Ping on those merge conflicts.

**Comment by Thynix** [comment]
Cough cough cough cough.

**Comment by ArneBab** [comment]
ping on the merge conflicts from my side, too

**Comment by ArneBab** [comment]
ping?

**Comment by ArneBab** [comment]
@toad ping on the merge conflicts again

**Comment by ArneBab** [comment]
Here’s a version with fixed merge errors. It needs re-review, though, because the code it patches changed quite a bit since 2016: https://github.com/hyphanet/fred/pull/991

**Pull request closed without merging**
