### PR TITLE
html-filter: allow summary and details html element. Thanks to naejadu

### PR DESCRIPTION
**Pull request by ArneBab**

### CODE REVIEW

**Review by Bombe — CHANGES_REQUESTED** [review]
Where’s the test?

**Comment by ArneBab** [comment]
@Bombe good point! Thank you!

**Comment by ArneBab** [comment]
@Bombe I added a test now

**Comment by ArneBab** [comment]
> Where’s the test?

The test is now included.

**Review by Bombe — APPROVED** [review]

**Pull request merged**
