### PR TITLE
Convert tabs to spaces Master PR no EOL whitespace trimming

### PR DESCRIPTION
**Pull request by Juiceman**
Zap all tabs to spaces for entire codebase. Did not remove end-of-line whitespace in order for others to convert their code with a simple find and replace script.

Other outstanding PR will be converted also.

### CODE REVIEW

**Comment by Bombe** [comment]
Okay, @Juiceman, please, just **STOP**.

1. “Taking care of other PRs” meant “rebase them and verify them _after_ the initial reformat was merged,” not before. Nobody wants to check 300 files on dozens of pull requests, and we _have_ to check each and every one of them.
2. The changes you are doing have not been discussed, even though we have now mentioned multiple times that, should we choose to do this big change, it _needs_ to be discussed _before_ any changes are made.
3. The Google Java Style Guide actually says “2 spaces per indentation level,” not 4.

That being said, I don’t even know why we put the Google style guide in our contribution guide, but that can very well be part of the _discussion we need to have about this_. We should probably take this to the mailing list (or FMS?) to get a couple more people involved, or we could decide it meritocratically? 😁 @ArneBab, what do you think?

**Comment by ArneBab** [comment]
@Bombe I think FMS is a good place for the discussion. There are several people there who already wrote patches, and the main advantage is to get rid of the cost of IDEs breaking the indentation style. Though I think that people who contribute the most should get a veto. I’m still a burned child from experiencing group decisions where the decision went against the preference of the people who later were the only ones who actually did the work.

**Comment by ArneBab** [comment]
@Bombe I need the PRs reformatted and filed before merging the change, because I don’t want to merge a big formatting change if can’t be sure that all PR will be preserved with at most the amount of conflicts they have now.

**Comment by Bombe** [comment]
> @Bombe I think FMS is a good place for the discussion. There are several people there who already wrote patches, and the main advantage is to get rid of the cost of IDEs breaking the indentation style. Though I think that people who contribute the most should get a veto. I’m still a burned child from experiencing group decisions where the decision went against the preference of the people who later were the only ones who actually did the work.

Hmm, on second thought, in FMS we only have the freenet board which is full of trolls… how do we avoid getting bogged down by people who never planned to contribute any code? 🙁 We would probably need to establish deadlines for certain phases of the discussion which would need to be in the general area of weeks, in order to allow most people to contribute. Not everybody can react within 24 hours or similarly short time frames.

> @Bombe I need the PRs reformatted and filed before merging the change, because I don’t want to merge a big formatting change if can’t be sure that all PR will be preserved with at most the amount of conflicts they have now. I can then compare them against the to-be-merged branch from next.

I think I know what you mean but this seems like it would add a _lot_ of useless work to the process. @Juiceman already agreed to take care of the PRs, which means that after we merge the whitespace change (should we choose to) and the subsequent rebasing of all PRs by @Juiceman the PRs will look pretty much exactly like now, cutting down additional work due to the whitespace changes to pretty much 0. To me that sounds way better… 😀

**Comment by ArneBab** [comment]
> Hmm, on second thought, in FMS we only have the freenet board which is full of trolls… how do we avoid getting bogged down by people who never planned to contribute any code? 🙁 We would probably need to establish deadlines for certain phases of the discussion which would need to be in the general area of weeks, in order to allow most people to contribute. Not everybody can react within 24 hours or similarly short time frames.

Should we do it in FLIP, then, and only announce in FMS/Sone/ML/libera chat? People can join either with pristine FLIP or with the FLIRCP plugin (the latter is less convenient to use but just works).

> > @Bombe I need the PRs reformatted and filed before merging the change, because I don’t want to merge a big formatting change if can’t be sure that all PR will be preserved with at most the amount of conflicts they have now. I can then compare them against the to-be-merged branch from next.
> 
> I think I know what you mean but this seems like it would add a _lot_ of useless work to the process. @Juiceman already agreed to take care of the PRs, which means that after we merge the whitespace change (should we choose to) and the subsequent rebasing of all PRs by @Juiceman the PRs will look pretty much exactly like now, cutting down additional work due to the whitespace changes to pretty much 0. To me that sounds way better… 😀

Where do you see the additional work? Rebasing/merging can easily be done against the not-yet-merged changed next-branch (Juiceman will have that locally). An option to make review here on github easier could be to file the new PRs against the changed next branch. The approach would then be:

- copy the changed next under a temporary name into the hyphanet/fred repository (i.e. `next--style-google`)
- file the changed PRs against this `next--style-google` branch.
- verify whether the diffs of the old PRs (without whitespace) are the same as the new PRs, except for those for which there are already current conflicts that had to be resolved.

**Comment by Bombe** [comment]
> > Hmm, on second thought, in FMS we only have the freenet board which is full of trolls… how do we avoid getting bogged down by people who never planned to contribute any code? 🙁 We would probably need to establish deadlines for certain phases of the discussion which would need to be in the general area of weeks, in order to allow most people to contribute. Not everybody can react within 24 hours or similarly short time frames.
> 
> Should we do it in FLIP, then, and only announce in FMS/Sone/ML/libera chat? People can join either with pristine FLIP or with the FLIRCP plugin (the latter is less convenient to use but just works).

I think using chat for this makes it even worse… we need to find a time that works for everyone, with the additional problem that we don’t even know who “everyone” is. And then it requires everyone to be present for all of the conversation.

I think we don’t have much choice beyond FMS. Let’s hope we can largely ignore obvious trolls… 🙂 

> If yes, we could schedule a handful of days for the discussion (just don’t plan over easter: I’m away then).

Yeah, right, as if _I_ am free over easter… 😄 

> > > @Bombe I need the PRs reformatted and filed before merging the change, because I don’t want to merge a big formatting change if can’t be sure that all PR will be preserved with at most the amount of conflicts they have now. I can then compare them against the to-be-merged branch from next.
> > 
> > I think I know what you mean but this seems like it would add a _lot_ of useless work to the process. @Juiceman already agreed to take care of the PRs, which means that after we merge the whitespace change (should we choose to) and the subsequent rebasing of all PRs by @Juiceman the PRs will look pretty much exactly like now, cutting down additional work due to the whitespace changes to pretty much 0. To me that sounds way better… 😀
> 
> Where do you see the additional work? Rebasing/merging can easily be done against the not-yet-merged changed next-branch (Juiceman will have that locally). An option to make review here on github easier could be to file the new PRs against the changed next branch. The approach would then be:
> 
>     * copy the changed next under a temporary name into the hyphanet/fred repository (i.e. `next--style-google`)
> 
>     * file the changed PRs against this `next--style-google` branch.
> 
>     * verify whether the diffs of the old PRs (without whitespace) are the same as the new PRs, except for those for which there are already current conflicts that had to be resolved.

The additional work I see is that as long as the big change hasn’t been merged, the PRs will show the difference to `next` and not to some arbitrary other branch, i.e. all whitespace changes are in every PR, which means that every PR is for 1300 files and you don’t even know where the changes are. That _does_ sound like a fuckton of useless work to me. 🙂

I might be wrong here but I don’t think that the creator of a PR can choose which branch will be used to show the diff, because that sounds like it would allow sneaking in changes from other PRs when a maintainer doesn’t pay attention.

**Comment by ArneBab** [comment]
> FMS only choice

OK, then let’s do that.

> The additional work I see is that as long as the big change hasn’t been merged, the PRs will show the difference to next and not to some arbitrary other branch, i.e. all whitespace changes are in every PR, which means that every PR is for 1300 files and you don’t even know where the changes are. That does sound like a fuckton of useless work to me.

The PRs can be filed against the renamed next and after merging, we  can change the target  branch (clicking edit for the title allows changing the target branch, but not the source-branch).

**Pull request closed without merging**
