### PR TITLE
Add missing Global flag to GetFailed FCP message. Thanks to oishii!

### PR DESCRIPTION
**Pull request by ArneBab**
(bug reported by oishii@e-FUmCyxfF9D… on FMS)

### CODE REVIEW

**Comment by Bombe** [comment]
Oh, come on, @ArneBab, really? No test? 😀

**Comment by ArneBab** [comment]
> Oh, come on, @ArneBab, really? No test? 😀

Argh … I just wanted to get this commited so I could merge the other PR without leaving local state. Let me add a tag …

**Comment by ArneBab** [comment]
I’ll investigate later (another day) how FCP Messages can be tested cleanly.

**Review by Juiceman — APPROVED** [review]

**Comment by Bombe** [comment]
> I’ll investigate later (another day) how FCP Messages can be tested cleanly.

It looks like FCP messages can be rather easily created so a test for this should be a breeze. 🙂

**Comment by Bombe** [comment]
https://github.com/Bombe/fred/tree/add-tests/pr-908-global-flag adds a simple test for the flag.

**Comment by ArneBab** [comment]
@Bombe very cool — thank you!

**Comment by ArneBab** [comment]
And merged — thanks a lot, @Bombe @Juiceman !

**Pull request merged**
